[package]
name = "wsl2-bridge-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2" # optional, for file logging
windows-sys = { version = "0.61.2", features = [
    "Win32_Security",
    "Win32_System",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
] }
clap = { version = "4.5.51", features = ["derive"] }
home = "0.5.12"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
